<?php 

$str ="<?php if (!defined('BASEPATH')) exit('No direct script access allowed');";
$str .="\n\n\n\n/* $c_file */
    /* MPAMPAM CRUD GENERATOR */
    /* PENGEMBANG : MPAMPAM */
    /* EMAIL : MPAMPAM5@GMAIL.COM */
    /* FACEBOOK : https://www.facebook.com/mpampam */
    /* Generated by MPAMPAM CRUD GENERTOR ".date('Y-m-d H:i:s')." */
    /* https://mpampam.com */";


$created_file_controller = $str;
